language: objective-c
osx_image: xcode9.4

env:
  global:
    - PROJECT='SwifterSwift.xcodeproj'
    - IOS_SCHEME='SwifterSwift-iOS'
    - TVOS_SCHEME='SwifterSwift-tvOS'
    - WATCHOS_SCHEME='SwifterSwift-watchOS'
    - MACOS_SCHEME='SwifterSwift-macOS'
    - IOS_DESTINATION='platform=iOS Simulator,name=iPhone X'
    - TVOS_DESTINATION='platform=tvOS Simulator,name=Apple TV 4K (at 1080p)'
    - WATCHOS_DESTINATION='name=Apple Watch - 42mm'
    - MACOS_DESTINATION='platform=OS X'


before_install:
  - bundle install
  - brew update
  - brew outdated xctool || brew upgrade xctool
script:
  - set -o pipefail
  - swift --version
  - xcodebuild clean build test -project "$PROJECT" -scheme "$IOS_SCHEME" -destination "$IOS_DESTINATION" | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild-ios.json" xcpretty -f `xcpretty-json-formatter`
  - bash <(curl -s https://codecov.io/bash) -cF ios -J 'SwifterSwift'
  - xcodebuild clean build test -project "$PROJECT" -scheme "$TVOS_SCHEME" -destination "$TVOS_DESTINATION" | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild-tvos.json" xcpretty -f `xcpretty-json-formatter`
  - bash <(curl -s https://codecov.io/bash) -cF tvos -J 'SwifterSwift'
  - xcodebuild clean build test -project "$PROJECT" -scheme "$MACOS_SCHEME" -destination "$MACOS_DESTINATION" | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild-macos.json" xcpretty -f `xcpretty-json-formatter`
  - bash <(curl -s https://codecov.io/bash) -cF osx -J 'SwifterSwift'
  - xcodebuild clean build -project "$PROJECT" -scheme "$WATCHOS_SCHEME" -destination "$WATCHOS_DESTINATION" | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild-watchos.json" xcpretty -f `xcpretty-json-formatter`
  - swiftlint lint
  - bundle exec danger --verbose
  - pod lib lint
